### PR TITLE
Fix pr #72

### PR DESCRIPTION
**Pull request by matthewford**
Fixes the merge conflict in #72

### CODE REVIEW

**Comment by matthewford** [comment]
@pedrofurtado any ideas on how to get rails 4 not to load the XML gem?

**Comment by pedrofurtado** [comment]
Hi, @matthewford ! Sorry, but I did not understand the purpose/motivations of PR and this question about rails 4 + xml. Can you explain with more details, please? 🍻 🤝 

You reused the source code of another open PR, is there any special reason for this?

Thanks a lot! 👍

**Comment by matthewford** [comment]
this pr is effectively the same but with a rebase, however might need to squash my commits due to faffing with getting the specs to pass on rails 4

**Comment by pedrofurtado** [comment]
We can follow the progress of this feature here, including docs and so on: https://github.com/heapsource/active_model_otp/pull/87 🤝 🍻

**Pull request closed without merging**
