### PR TITLE
Add support for ruby 3.0

### PR DESCRIPTION
**Pull request by dmitry-ilyashevich**
Updated `rotp` with ruby 3.0 support, made small fix in `active_model_otp`, to support ruby 3.0

### CODE REVIEW

**Comment by mattbrictson** [comment]
I'm using this branch for a Rails 6.1 / Ruby 3.0 app. So far, so good. Would love to see this merged!

**Comment by pedrofurtado** [comment]
Any news about it? 🤝

**Comment by pedrofurtado** [comment]
pinging: @robertomiranda 👍

**Review by robertomiranda — APPROVED** [review]
Looks good, thank you 👍

**Comment by pedrofurtado** [comment]
@robertomiranda When you have time, could you please release a official version with Ruby 3 support? Today, we are using a fork with this PR inside it, but is better a oficial release 😄 🤝

**Pull request merged**
